quarkus.http.port=8085

quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.image-name=postgres:16
quarkus.datasource.devservices.db-name=kpis_db
quarkus.datasource.jdbc.max-size=8

%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/kpis_db
%prod.quarkus.datasource.username=postgres
%prod.quarkus.datasource.password=postgres

quarkus.hibernate-orm.database.generation=update

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
